### ISSUE TITLE
php icon is too big

### ISSUE THREAD

**Issue by amir-s** [jsartisan/jsartisan-minimalistic-ui#3]
Php files have a big icon with big font.
```css
.php-icon{
  .di;
  .bi;
  content: '\e63d';
  color: #728eb6;
}
```

currently I fixed it with:

```css
.php-icon {
    font-size: inherit;
    font-family: inherit;
    top: 0px !important;
}
```
